clipboard_control write-clipboard read-clipboard

# --- Fonts ---

font_family         monospace
bold_font           auto
italic_font         auto
bold_italic_font    auto

font_size           10.0

disable_ligatures   never

font_features       none

box_drawing_scale   0.001, 1, 1.5, 2

# --- Cursor ---

# --- Tabs ---
tab_bar_edge    top
tab_bar_style   slant