# =============================================================================
# appearance.conf — Gaps, bordes y colores de ventanas
# =============================================================================

# --- Gaps
gaps inner 2
gaps outer 5
smart_gaps on
hide_edge_borders smart

# --- Bordes
for_window [class=".*"] border pixel 2
default_border pixel 2
default_floating_border pixel 2

# --- Paleta (Catppuccin Mocha)
set $base       #1e1e2e
set $blue       #89b4fa
set $red        #f38ba8
set $surface    #313244
set $text       #cdd6f4

# --- Colores de ventanas         border    bg      text    indicator child_border
client.focused          $blue    $base    $text   $blue    $blue
client.focused_inactive $surface $base    $text   $surface $surface
client.unfocused        $surface $base    $text   $surface $surface
client.urgent           $red     $base    $text   $red     $red