# =============================================================================
# autostart.conf — Aplicaciones que inician con la sesión
# =============================================================================

# XDG autostart (.desktop files)
exec --no-startup-id dex --autostart --environment i3

# Bloqueo de pantalla al suspender
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# Applets de sistema
exec --no-startup-id nm-applet
# exec --no-startup-id blueman-applet

# Notificaciones
exec_always --no-startup-id "killall dunst; dunst -config ~/.config/dunst/dunstrc"