# =============================================================================
# bar.conf — Barra de estado (i3bar + i3status)
# =============================================================================

bar {
    status_command i3status --config ~/.config/i3/i3status.conf
 
    colors {
        # Fondo/texto de la barra
        background #1e1e2e
        statusline #cdd6f4
        separator  #585b70
 
        # Workspaces:           border   background  text
        focused_workspace      #89b4fa   #313244     #cdd6f4
        active_workspace       #45475a   #1e1e2e     #bac2de
        inactive_workspace     #1e1e2e   #1e1e2e     #585b70
        urgent_workspace       #f38ba8   #1e1e2e     #f38ba8
        binding_mode           #cba6f7   #1e1e2e     #cba6f7
    }
}