# =============================================================================
# bar.conf — Barra de estado (i3bar + i3status)
# =============================================================================

bar {
    status_command i3status
}